# Site settings
title: Tamas Hudak
email: contact@thudak.com
description: "Freelance Software Engineer"
url: "https://thudak.com"
baseurl: ""
github-username: tomhudak
twitter-username: tamas_hudak
medium-username: tamashudak
linkedin-username: tamas-hudak

google_analytics: G-E3M29N1MHD

exclude:
  - .devcontainer
  - .vscode
  - .env
  - deploy.sh

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      image: /assets/summer.jpeg
